version: '3'

services:
  sari:
    image: sari:latest
    container_name: sari
    env_file: ./${CONFIG:-config}/env_file
    command: up --yes
    volumes:
        - ./${CONFIG:-config}:/app/config
