
name: Build and publish package

on:
  create:
    tags:
      - 'v*.*.*'
env:
  IMAGE_NAME: sari

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_TAG=$(echo ${GITHUB_REF:10})
        echo IMAGE_ID=$IMAGE_ID
        echo IMAGE_TAG=$IMAGE_TAG
        docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
        docker push $IMAGE_ID:$IMAGE_TAG
