
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: cached venv
      uses: actions/cache@v2
      with:
        path: .venv/
        key: ${{ runner.os }}.venv

    - name: Install Pipenv
      run: pip install --disable-pip-version-check pipenv

    - name: Install DEV Packages
      run: PIPENV_VENV_IN_PROJECT=1 pipenv sync --dev

    - name: Run all tests
      run: pipenv run pytest -v
